import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { cn } from '@/lib/utils/ui'
import '@/app/styles/globals.css'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

type RootLayoutProps = {
  children: React.ReactNode
}

const RootLayout = ({
  children,
}: RootLayoutProps) => {
  return (
    <ClerkProvider>
      <html lang="en" className='light'>
        <body className={cn(
          'min-h-screen font-sans antialiased grainy',
          inter.className
        )}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}

export default RootLayout
